version: "3.9"
services:

  grafana:
    image: grafana/grafana:9.2.3
    hostname: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_DOMAIN: localhost
    ports:
      - '0.0.0.0:3000:3000'
    user: '0'
    volumes:
      - ./grafanadata:/var/lib/grafana
    networks:
      - grafana
    deploy:
      replicas: 1

  loki:
    image: grafana/loki:2.9.1
    hostname: loki
      #log.level: debug
    networks:
      - loki
      - grafana
    deploy:
      replicas: 1

  promtail:
    image: grafana/promtail:2.9.1
    hostname: promtail
    volumes:
      - ./promtaildata/config.yml:/etc/promtail/config.yml:ro
      - ./GeoIPLite/GeoLite2-City_20231107/GeoLite2-City.mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb:ro
    command: 
      - '-config.file=/etc/promtail/config.yml'
    networks:
      - loki
      - promtail
    deploy:
      replicas: 1
  
  geoipupdate:
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    environment:
      - 'GEOIPUPDATE_ACCOUNT_ID_FILE=/run/secrets/GEOIPUPDATE_ACCOUNT_ID'
      - 'GEOIPUPDATE_LICENSE_KEY_FILE=/run/secrets/GEOIPUPDATE_LICENSE_KEY'
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-City'
    volumes:
      - geoipupdate_data:/usr/share/GeoIP
    secrets:
      - GEOIPUPDATE_ACCOUNT_ID
      - GEOIPUPDATE_LICENSE_KEY
    deploy:
      replicas: 1

secrets:
  GEOIPUPDATE_ACCOUNT_ID:
    file: ./secrets/GEOIPUPDATE_ACCOUNT_ID.txt
  GEOIPUPDATE_LICENSE_KEY:
    file: ./secrets/GEOIPUPDATE_LICENSE_KEY.txt

volumes:
  grafanadata: {}
  geoipupdate_data: {}


networks:
  grafana: {}
  loki: {}
  promtail:
    name: promtail
