version: "3"
services:

  syslog:
    image: lscr.io/linuxserver/syslog-ng:latest
    container_name: syslog
    hostname: syslog
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./log:/var/log #optional
      - geoip:/usr/share/GeoIP
    ports:
      - 514:514/tcp
    depends_on:
      - geoip
    networks:
      - promtail
    deploy:
      replicas: 1

  geoip:
    image: maxmindinc/geoipupdate
    container_name: geoip
    restart: on-failure
    environment:
      - 'GEOIPUPDATE_ACCOUNT_ID_FILE=/run/secrets/gad'
      - 'GEOIPUPDATE_LICENSE_KEY_FILE=/run/secrets/gid'
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-City'
    secrets:
      - gad
      - gid
    volumes:
      - geoip:/usr/share/GeoIP
    deploy:
      replicas: 1


secrets:
  gad:
    file: ./secrets/GEOIPUPDATE_ACCOUNT_ID.txt
  gid:
    file: ./secrets/GEOIPUPDATE_LICENSE_KEY.txt


volumes:
  geoip: {}

networks:
  promtail:
     external: true
